name: Composite action template
description: |
  This action does nothing meaningful.

inputs:
  example-input:
    description: A useless input as an example
    required: true
outputs:
  example-output:
    description: You know it.
    value: ${{ steps.generate-output.outputs.example-output }}
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if test "${{ runner.debug }}" = "1"; then
          set -x
        fi
        echo "here is your input: ${{ inputs.example-input }}."
    - id: generate-output
      shell: bash
      run: |
        if test "${{ runner.debug }}" = "1"; then
          set -x
        fi
        echo "example-output=here is your output" >> ${GITHUB_OUTPUT}
