name: Self Test

on:
  push: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  self-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Invoke action
        id: self-test
        uses: ./
        with:
          type: npm
          file: test/big-package.json
      - name: Show outputs
        env:
          OUTPUTS: ${{ toJson(steps.self-test.outputs) }}
        run: |
          echo "${OUTPUTS}"
      - name: Assert results
        run: |
          if test "${{ steps.self-test.outputs.version }}" != "1.2.3"; then
            echo "Expected version 1.2.3, got ${{ steps.self-test.outputs.version }}!"
            exit 1
          fi
